import logging
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, replace

from openmind.inference.model.surprise import Surprise
from openmind.inference.service.action_readings import ActionReadings
from openmind.structure.model.value import Value
from openmind.world.model.action import Action
from openmind.world.model.state import State

logger = logging.getLogger(__name__)

#: What a condition reads as: a reading, how it is compared, and to what.
type Condition = tuple[str, str, Value]


@dataclass(frozen=True, slots=True)
class Deduced:
    """A condition every legal action was found to satisfy, and what it was worth finding out.

    `excluded` is how many of the candidates that were not legal it rules out, which is what says whether it explains
    anything: a condition every candidate satisfies is true and useless. `given` is the reading and value it holds
    under, where it holds only for some of them — what a piece of one kind may do says nothing about another kind."""

    condition: Condition
    excluded: int
    covered: int
    given: tuple[Condition, ...] = ()

    @property
    def readable(self) -> str:
        reading, relation, value = self.condition
        if relation == "== reading":
            held = f"{reading} is {value}"
        elif relation == "!= reading":
            held = f"{reading} is not {value}"
        else:
            held = f"{reading} {relation} {value!r}"
        if not self.given:
            return held
        where = " and ".join(f"{name} {comparison} {expected!r}" for name, comparison, expected in self.given)
        return f"where {where}, {held}"


class RuleDeducer:
    """Works out what makes an action legal, from nothing but which actions are legal.

    A game may be declared the short way: its legal actions generated by whatever the integrator already had, with
    nothing said about what makes them legal. OMF can play that game and can reason about nothing in it — there is no
    constraint to relax, no rule to read. This is how it gets them back.

    A constraint is a condition every legal action satisfies. So the candidates are gathered, the legal ones are
    marked, and every condition the readings allow is tested against them: what holds for all the legal ones is a
    candidate constraint, and what it rules out of the rest is what says it was worth finding. A condition that holds
    only for actions of a certain kind — what a knight may do — is found the same way, within the candidates that
    kind covers.

    What comes out is opinions, not beliefs: they explain every action OMF has seen and the next position may
    contradict them. So the next thing to do with them is to try to break them — build the position that would refute
    a rule, ask what is legal there, and keep what survives."""

    def __init__(self, action_readings: ActionReadings | None = None) -> None:
        self._readings = ActionReadings() if action_readings is None else action_readings
        #: What broke a rule that had stood a long time: the rare rules of the game, as they are met.
        self.surprises: tuple[Surprise, ...] = ()
        #: The actions the game refuses that no rule found can refuse: what the readings cannot yet tell apart.
        self.unexplained: tuple[Mapping[str, Value], ...] = ()

    def conjunction(
        self,
        rules: Sequence[Deduced],
        examples: Sequence[tuple[Mapping[str, Value], bool]],
        most: int | None = None,
        cost: float = 0.0,
    ) -> tuple[Deduced, ...]:
        """The few rules that together tell the legal actions from the rest, chosen from what has been deduced.

        Every rule on its own is a condition the legal actions happen to satisfy, and a hundred of them together are
        useless in both directions: some were true only of the positions they were found in, and refuse legal actions
        elsewhere; the rest let almost everything through. What is wanted is the conjunction — the handful that,
        taken together, refuse the illegal and nothing else.

        It is built one rule at a time: whichever rule rules out the most of what is still wrongly allowed goes in
        next, and a rule costing no legal action is always taken before one that costs some.

        `cost` is how much of what is still legal a rule may refuse to be worth taking — none of it by default.
        Allowing some is how the last few actions the game refuses get ruled out, and allowing too much is how a
        deduced game ends up narrower than the real one: a rule that refuses a tenth of the legal moves to rule out a
        handful of illegal ones has made OMF a worse player, not a better-informed one. What it lets through in a
        position it has never seen is a discovery waiting to happen; what it refuses is a move it will never make."""
        allowed = [readings for readings, legal in examples if not legal]
        legal = [readings for readings, was_legal in examples if was_legal]
        keeping = list(rules)
        chosen: list[Deduced] = []
        while allowed and (most is None or len(chosen) < most):
            best, worth = None, (0.0, 0.0)
            for rule in keeping:
                rules_out = sum(1 for readings in allowed if not self._speaks(rule, readings))
                if not rules_out:
                    continue
                costs = sum(1 for readings in legal if not self._speaks(rule, readings))
                # A rule costing no legal action is taken over any that costs one, however much it rules out: what is
                # wanted is everything the game refuses ruled out and as little else as possible. Where none is left
                # that costs nothing, the cheapest per action ruled out is taken.
                if costs and costs > max(cost * len(legal), 0.0):
                    continue
                held = (1.0, float(rules_out)) if not costs else (0.0, rules_out / costs)
                if held > worth:
                    best, worth = rule, held
            if best is None:
                break
            chosen.append(best)
            keeping.remove(best)
            allowed = [readings for readings in allowed if self._speaks(best, readings)]
            legal = [readings for readings in legal if self._speaks(best, readings)]
        illegal = sum(1 for _, legal in examples if not legal)
        logger.info("Chose %d rules of %d: %d illegal actions still allowed of %d", len(chosen), len(rules), len(allowed), illegal)
        self.unexplained = tuple(allowed)
        if allowed:
            logger.warning(
                "%d of %d actions the game refuses are ones no rule can refuse: nothing read of them tells them from "
                "the legal ones, so either a reading is missing or what refuses them isn't about the action at all",
                len(allowed),
                illegal,
            )
        return tuple(chosen)

    def _speaks(self, rule: Deduced, readings: Mapping[str, Value]) -> bool:
        """Whether the rule lets that candidate through: it holds of it, or has nothing to say about it."""
        return not self._within(readings, rule.given) or self._holds(readings, rule.condition)

    def _within(self, readings: Mapping[str, Value], given: Sequence[Condition]) -> bool:
        """Whether the rule speaks of that candidate at all: everything it holds under holds of it."""
        return all(self._holds(readings, condition) for condition in given)

    def refined(
        self,
        rules: Sequence[Deduced],
        examples: Sequence[tuple[Mapping[str, Value], bool]],
        rounds: int = 6,
        splits: int = 12,
        cost: float = 0.0,
    ) -> tuple[Deduced, ...]:
        """Rules chosen, then chosen again, until nothing the game refuses is still allowed or nothing more can be
        found.

        A conjunction that lets nothing wrong through is what a rule of a game is. Where some actions are still
        allowed that the game refuses, they are not noise: they are what the rules say in a case nothing has been
        said about yet. So the case is looked for — the readings that tell those actions apart from the legal ones —
        and within each, what the legal actions have in common is deduced anew. A rule found that way holds under
        more than one condition: where a pawn moves straight ahead, it lands on nothing.

        It stops when nothing is left to explain, or when a round explains nothing more than the last."""
        chosen = self.conjunction(rules, examples, cost=cost)
        known = list(rules)
        for _ in range(rounds):
            if not self.unexplained:
                break
            before = len(self.unexplained)
            found = self._within_cases(known, examples, self.unexplained, splits)
            if not found:
                break
            known = [*known, *found]
            chosen = self.conjunction(known, examples, cost=cost)
            if len(self.unexplained) >= before:
                break
        return chosen

    def _within_cases(
        self,
        rules: Sequence[Deduced],
        examples: Sequence[tuple[Mapping[str, Value], bool]],
        residue: Sequence[Mapping[str, Value]],
        splits: int,
    ) -> list[Deduced]:
        """What the legal actions have in common within each case the residue points at.

        The cases worth looking at are the ones the still-allowed actions fall into: a reading whose value they share
        with only some of the legal ones is a case where something else must be being said."""
        legal = [readings for readings, allowed in examples if allowed]
        found: list[Deduced] = []
        for held in self._cases(legal, residue, splits):
            within = [(readings, allowed) for readings, allowed in examples if self._within(readings, held)]
            inside = [readings for readings, allowed in within if allowed]
            if inside and len(inside) < len(legal):
                found.extend(self._holding(within, inside, held))
        return found

    def _cases(
        self, legal: Sequence[Mapping[str, Value]], residue: Sequence[Mapping[str, Value]], splits: int
    ) -> list[tuple[Condition, ...]]:
        """The cases to look within: pairs of conditions the still-allowed actions satisfy, from the readings that
        take few enough values to be worth splitting on."""
        countable = [
            reading
            for reading in sorted(legal[0])
            if len({readings.get(reading) for readings in legal}) <= splits
        ]
        cases: list[tuple[Condition, ...]] = []
        for first in countable:
            for value in sorted({readings.get(first) for readings in residue}, key=repr):
                one = (first, "==", value)
                cases.append((one,))
                for second in countable:
                    if second <= first:
                        continue
                    for other in sorted({readings.get(second) for readings in residue}, key=repr):
                        cases.append((one, (second, "==", other)))
        return cases

    def allows(self, rules: Sequence[Deduced], readings: Mapping[str, Value]) -> bool:
        """Whether the rules let that candidate through: every rule that speaks of it holds of it. A rule holding
        only where something else does says nothing about a candidate that something else doesn't hold of."""
        return all(
            self._holds(readings, rule.condition)
            for rule in rules
            if self._within(readings, rule.given)
        )

    def scored(
        self, rules: Sequence[Deduced], examples: Sequence[tuple[Mapping[str, Value], bool]]
    ) -> tuple[int, int, int]:
        """What the rules are worth as a generator, on those candidates: how many legal actions they let through, how
        many they wrongly refuse, and how many illegal ones they wrongly allow.

        Rules that only ever had to agree with legal actions can refuse none of them and still be useless — they let
        everything else through too. Both ways of being wrong have to be counted, or nothing has been measured."""
        allowed = missed = wrong = 0
        for readings, legal in examples:
            if self.allows(rules, readings):
                allowed, wrong = (allowed + 1, wrong) if legal else (allowed, wrong + 1)
            elif legal:
                missed += 1
        return allowed, missed, wrong

    def unforeseen(
        self, considered: Sequence[Action], legal: Sequence[Action], seen: int = 0, state: State | None = None
    ) -> tuple[Action, ...]:
        """The legal actions that were not among the candidates at all: what OMF did not know could be done.

        A rule can be wrong in two ways. It can say something is legal that isn't, which a candidate refutes; or the
        game can do something the rules never spoke of — castling, a pawn becoming a queen — which no candidate can
        refute, because none was ever offered. The second is a discovery, and meeting it is the moment to work out
        what it was: an action of a kind never considered, or one carrying a value never seen.

        What it had already seen is how surprising it is. Something the game could always have done, met for the
        first time after a thousand actions, is the rarest thing it knows about itself."""
        known = {self._shape(action) for action in considered}
        names = {action.name for action in considered}
        found = tuple(action for action in legal if self._shape(action) not in known)
        for action in found:
            why = "of a kind never considered" if action.name not in names else "carrying a value never seen"
            self.surprises = (
                *self.surprises,
                Surprise(f"{action.name} {why}: {dict(action.parameters)}", seen, state or State(()), action),
            )
            logger.warning("Discovered: %s %s after %d actions", action.name, why, seen)
        return found

    def _shape(self, action: Action) -> tuple[object, ...]:
        """What tells one kind of action from another: its name and the values its parameters take."""
        return (action.name, tuple(sorted((name, value) for name, value in action.parameters)))

    def examples(
        self, state: State, candidates: Sequence[Action], legal: Callable[[Action], bool]
    ) -> tuple[tuple[dict[str, Value], bool], ...]:
        """Every candidate read, with whether it was legal."""
        return tuple((self._readings.of(state, candidate), legal(candidate)) for candidate in candidates)

    def learn(
        self,
        standing: Sequence[Deduced],
        examples: Sequence[tuple[Mapping[str, Value], bool]],
        given: Sequence[str] = (),
        state: State | None = None,
    ) -> tuple[Deduced, ...]:
        """What is left of what was believed, once these actions have had their say, and what they newly suggest.

        A rule can only be found where there are legal actions to find it in: nothing about how a bishop moves can be
        deduced from a position where no bishop can move. So every position both refutes what it contradicts and
        proposes what it shows, and a rule proposed now is tested by everything that comes after."""
        kept, surprises = self.refuted(standing, examples, state)
        self.surprises = (*getattr(self, "surprises", ()), *(one for one in surprises if one.rare))
        known = {(rule.given, rule.condition) for rule in kept}
        found = [rule for rule in self.deduce(examples, given) if (rule.given, rule.condition) not in known]
        return tuple(sorted((*kept, *found), key=lambda one: (-one.excluded, one.readable)))

    def deduce(
        self, examples: Sequence[tuple[Mapping[str, Value], bool]], given: Sequence[str] = ()
    ) -> tuple[Deduced, ...]:
        """What every legal action among those examples has in common, most telling first.

        `given` names readings to look within as well as across: a condition that holds for every legal action whose
        source holds a knight is found where `given` names the reading that says so."""
        legal = [readings for readings, allowed in examples if allowed]
        if not legal:
            return ()
        found = list(self._holding(examples, legal, ()))
        for reading in given:
            for value in sorted({readings.get(reading) for readings in legal}, key=repr):
                held = ((reading, "==", value),)
                within = [(readings, allowed) for readings, allowed in examples if self._within(readings, held)]
                inside = [readings for readings, allowed in within if allowed]
                if inside:
                    found.extend(self._holding(within, inside, held))
        return tuple(sorted(found, key=lambda one: (-one.excluded, one.readable)))

    def _holding(
        self,
        examples: Sequence[tuple[Mapping[str, Value], bool]],
        legal: Sequence[Mapping[str, Value]],
        given: tuple[Condition, ...],
    ) -> list[Deduced]:
        """Every condition each of those legal actions satisfies, with what it rules out of the rest."""
        found: list[Deduced] = []
        for condition in self._conditions(legal):
            if not all(self._holds(readings, condition) for readings in legal):
                continue
            excluded = sum(1 for readings, allowed in examples if not allowed and not self._holds(readings, condition))
            if excluded:
                found.append(Deduced(condition, excluded, len(legal), given))
        return found

    def _conditions(self, legal: Sequence[Mapping[str, Value]]) -> list[Condition]:
        """Every condition worth testing: what a reading is, what it is one of, where a number stands, and which
        readings are always the same as one another — which is what says a piece moved is the mover's own."""
        conditions: list[Condition] = list(self._same(legal))
        for reading in sorted(legal[0]):
            values = {readings.get(reading) for readings in legal}
            if len(values) == 1:
                conditions.append((reading, "==", values.pop()))
                continue
            numbers = [value for value in values if isinstance(value, int | float) and not isinstance(value, bool)]
            if len(numbers) == len(values):
                conditions.append((reading, "<=", max(numbers)))
                conditions.append((reading, ">=", min(numbers)))
            conditions.append((reading, "in", tuple(sorted(values, key=repr))))
        return conditions

    def _same(self, legal: Sequence[Mapping[str, Value]]) -> list[Condition]:
        """Pairs of readings that were the same in every legal action: a condition between two readings rather than
        between a reading and a value.

        A pair that was never the same is a condition too, and the one that says a piece isn't taken from its own
        side: what makes an action legal is as often two readings differing as two agreeing.

        Only readings of the same kind are compared. Python holds that False is 0, so a reading that says whether two
        cells line up would otherwise match one that counts what stands between them, and the nonsense would survive
        every test."""
        names = sorted(legal[0])
        found: list[Condition] = []
        for number, first in enumerate(names):
            for second in names[number + 1 :]:
                comparable = all(self._alike(readings.get(first), readings.get(second)) for readings in legal)
                if not comparable:
                    continue
                same = [readings.get(first) == readings.get(second) for readings in legal]
                if all(same):
                    found.append((first, "== reading", second))
                elif not any(same):
                    found.append((first, "!= reading", second))
        return found

    def _alike(self, one: Value, other: Value) -> bool:
        """Whether two readings are of the same kind: two truths, two numbers, or two of anything else."""
        return isinstance(one, bool) == isinstance(other, bool) and (
            isinstance(one, int | float) == isinstance(other, int | float)
        )

    def _holds(self, readings: Mapping[str, Value], condition: Condition) -> bool:
        reading, relation, value = condition
        held = readings.get(reading)
        if relation in ("== reading", "!= reading"):
            other = readings.get(str(value))
            if not self._alike(held, other):
                return False
            return held == other if relation == "== reading" else held != other
        if relation == "==":
            return held == value
        if relation == "in":
            return held in value  # type: ignore[operator]
        if not isinstance(held, int | float) or isinstance(held, bool):
            return False
        return held <= value if relation == "<=" else held >= value  # type: ignore[operator]

    def refuted(
        self,
        deduced: Sequence[Deduced],
        examples: Sequence[tuple[Mapping[str, Value], bool]],
        state: State | None = None,
    ) -> tuple[tuple[Deduced, ...], tuple[Surprise, ...]]:
        """Which of those rules survive the examples, and what broke the rest.

        A rule says every legal action satisfies a condition. One legal action that doesn't is enough to refute it —
        which is why the positions worth building are the ones where it might not hold.

        What broke a rule comes back as a surprise rather than as nothing: a rule broken after three thousand actions
        has met something the game rarely does, and that is worth saying out loud and keeping."""
        standing: list[Deduced] = []
        surprises: list[Surprise] = []
        for rule in deduced:
            within = [
                readings
                for readings, allowed in examples
                if allowed and self._within(readings, rule.given)
            ]
            counted = [readings for readings in within if not self._holds(readings, rule.condition)]
            if counted:
                surprise = Surprise(rule.readable, rule.covered, state or State(()), None, tuple(sorted(counted[0].items())))
                surprises.append(surprise)
                if surprise.rare:
                    logger.warning(
                        "Surprised: %s stood for %d actions and this position broke it", rule.readable, rule.covered
                    )
                else:
                    logger.debug("Refuted: %s, by %d legal actions", rule.readable, len(counted))
            else:
                standing.append(replace(rule, covered=rule.covered + len(within)))
        logger.info("%d rules stood, %d were broken by %d actions", len(standing), len(surprises), len(examples))
        return tuple(standing), tuple(surprises)
